---
# References
# Installing the right dependencies is tricky https://github.com/ajenti/ajenti/issues/815
# Installing Pip packages https://docs.ansible.com/ansible/pip_module.html

- name: Add public key for Ajenti Repo
  apt_key: url=http://repo.ajenti.org/debian/key state=present

- name: Add Ajenti Repo
  apt_repository: repo='deb http://repo.ajenti.org/debian main main debian' state=present

- name: Install support packages
  apt: name={{item}} state=installed
  with_items: support_packages

- name: Install Gevent from pypy
  pip:
    name: gevent
    version: 1.1b4
    extra_args: '-U'

- name: Install greenlet
  pip: name=greenlet

- name: Install Ajenti
  apt: name=ajenti state=present
  notify: Start Ajenti