---

- hosts: all

  roles:
    - { role: ap, tags: wireless }
    - { role: dhcp, tags: dhcp }
    - { role: router, tags: [iptables, router] }
    - { role: firewall, tags: [firewall, iptables]}
    - { role: ajenti, tags: ajenti }

  vars_files:
    - vars/main.yml