---

- hosts: all

  roles:
    - { role: ap, tags: wireless }
    - { role: dhcp, tags: dhcp }
    - { role: router, tags: router }
    - { role: ajenti, tags: ajenti }

  vars_files:
    - vars/main.yml