---
# References
# https://docs.ansible.com/ansible/iptables_module.html
# https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-using-iptables-on-ubuntu-14-04
# https://www.digitalocean.com/community/tutorials/a-deep-dive-into-iptables-and-netfilter-architecture

- name: Open port for SSH
  shell: iptables -A INPUT -p tcp --dport=22  -j ACCEPT

- name: Open port for incoming DNS requests from LAN
  shell: iptables -A INPUT -p udp --dport=53 -i wlan0 -j ACCEPT

- name: Open port for incoming DNS replies from WAN
  shell: iptables -A INPUT -p udp --sport=53 -i eth0 -m conntrack --ctstate=ESTABLISHED -j ACCEPT

- name: Open port for DHCP
  shell: iptables -A INPUT -p udp --dport=67 -i wlan0  -j ACCEPT

- name: Open port for Ajenti Web control Panel
  shell: iptables -A INPUT -p tcp --dport 8000 -j ACCEPT

- name: Allow responses to locally generated traffic
  shell: iptables -A INPUT -i eth0 -m conntrack --ctstate=RELATED,ESTABLISHED -j ACCEPT

- name: Append DROP rule to INPUT chain
  shell: iptables  -A INPUT -j DROP

- name: Save iptables rules
  shell: 'iptables-save > /etc/iptables/rules.v4'
