---

- name: Check if HostAPD is installed
  command: which hostapd
  ignore_errors: yes
  register: install_hostapd

- include: install_drivers.yml
  when: install_hostapd.rc == 1

- name: Copy interfaces file
  template: src=interfaces dest=/etc/network/interfaces
  notify: Restart Networking

- name: Copy HostAPD config file
  template: src=hostapd.conf.j2 dest=/etc/hostapd/hostapd.conf
  notify: Restart HostAPD

- name: Start HostAPD service now
  service: name=hostapd state=started enabled=yes