---

- name: Install AP packages
  apt: name=hostapd state=installed

- name: Copy interfaces file
  template: src=interfaces dest=/etc/network/interfaces

- name: Copy HostAPD config file
  template: src=hostapd.conf.j2 dest=/etc/hostapd/hostapd.conf

- name: Enable HostAPD on boot
  lineinfile: dest=/etc/default/hostapd regexp='#DAEMON_CONF=' state=present line='DAEMON_CONF="/etc/hostapd/hostapd.conf"'